### ISSUE TITLE
Typo and structure not behaving properly 

### ISSUE THREAD

**Issue by bigbaddevil7** [Lomeli12/MultiBlock-Tutorial#1]
On the website. in step 2 you have:
TileEntity tile = worldObj.getBlockTileEntity(x, y, z);
instead of 
TileEntity tile = worldObj.getTileEntity(x, y, z);

In the mod main class the blocks are registered wrong since all you need now is the class and the string. 

I'm not sure if this is a bug or not but the diamond block always spawns even after you break it, it gets replaced. Again not sure if this was intended or not.

The diamond block still spawns even after the multiblock is broken until the master block is removed. 

If the multiblock is partially broken it will not form until the whole structure is rebuilt.

At first I wasn't sure if I did something wrong when I first worked with it, but I copy pasta it and had those issues.

**Comment by Lomeli12** [comment]
getBlockTileEntity was renamed to getTileEntity in 1.7.x and above

See https://github.com/Lomeli12/MultiBlock-Tutorial/blob/master/src/main/java/multiblock/ItemSpecialBlock.java#L11

Yes, that's intended.

That's a bug.

That's also a bug.

thanks for the heads up.
